"""
Documentation Generator — Auto-generates docs from codebase analysis.
"""
import os
from typing import Dict, Any, Optional
from datetime import datetime


class DocGenerator:
    """Generates documentation from analysis results."""
    
    def __init__(self, repo_path: str, analysis_results: Optional[Dict[str, Any]] = None):
        self.repo_path = repo_path
        self.results = analysis_results or {}
        self.repo_name = os.path.basename(os.path.abspath(repo_path))
    
    def generate_full_docs(self) -> str:
        complexity = self.results.get('complexity', {})
        files = complexity.get('files', [])
        deps = self.results.get('dependencies', {})
        
        doc = f"# {self.repo_name} — Auto-Generated Documentation\n\n"
        doc += f"> Generated by **DevScope** on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n---\n\n"
        
        # Overview
        doc += "## Overview\n\n"
        doc += f"| Metric | Value |\n|---|---|\n"
        doc += f"| Files | {complexity.get('total_files', 0)} |\n"
        doc += f"| Functions | {complexity.get('total_functions', 0)} |\n"
        doc += f"| Health Score | {complexity.get('health_score', 0)}/100 |\n"
        doc += f"| Avg Complexity | {complexity.get('avg_complexity', 0)} |\n\n"
        
        # Hotspots
        hotspots = [f for f in files if f.get('max_complexity', 0) > 10]
        doc += f"## Complexity Hotspots ({len(hotspots)})\n\n"
        for h in sorted(hotspots, key=lambda x: x.get('max_complexity', 0), reverse=True)[:10]:
            doc += f"- `{h['path']}` — complexity {h.get('max_complexity', 0)}\n"
        
        # Dependencies
        doc += f"\n## Dependencies\n\n"
        doc += f"- Imports: {deps.get('import_count', 0)}\n"
        doc += f"- Calls: {deps.get('call_count', 0)}\n"
        
        doc += "\n---\n*Generated by DevScope*\n"
        return doc
    
    def save(self, output_path: str = None) -> str:
        if output_path is None:
            output_path = os.path.join(self.repo_path, 'DOCS.md')
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(self.generate_full_docs())
        return output_path

# Made with Bob
