"""
Modernization Planner for DevScope.

Generates prioritized modernization roadmaps based on:
- Complexity hotspots
- Circular dependencies
- Test coverage gaps
- AI-detected anti-patterns
"""

from typing import Dict, Any, List, Optional
from pathlib import Path
import logging
from ..graph.neo4j_client import Neo4jClient
from ..semantic.granite_client import GraniteClient

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ModernizationPlanner:
    """
    Generates modernization roadmaps for codebases.
    
    Analyzes:
    - Complexity hotspots (high cyclomatic complexity)
    - Circular dependencies
    - Test coverage gaps
    - Anti-patterns and modernization opportunities
    """
    
    COMPLEXITY_THRESHOLD = 10  # Functions with complexity > 10 are hotspots
    
    def __init__(self, repo_path: str, neo4j_client: Optional[Neo4jClient] = None,
                 granite_client: Optional[GraniteClient] = None):
        """
        Initialize modernization planner.
        
        Args:
            repo_path: Path to repository root
            neo4j_client: Optional Neo4j client (uses singleton if not provided)
            granite_client: Optional Granite client (creates new if not provided)
        """
        self.repo_path = Path(repo_path)
        self.neo4j_client = neo4j_client or Neo4jClient.get_instance()
        self.granite_client = granite_client or GraniteClient()
        
        self.issues = {
            'critical': [],
            'high': [],
            'medium': []
        }
    
    def generate_roadmap(self) -> str:
        """
        Generate complete modernization roadmap.
        
        Returns:
            Markdown formatted modernization roadmap
        """
        logger.info("Generating modernization roadmap...")
        
        # Gather issues
        self._find_complexity_hotspots()
        self._find_circular_dependencies()
        self._find_test_coverage_gaps()
        self._find_anti_patterns()
        
        # Build roadmap
        roadmap = "# Modernization Roadmap\n\n"
        roadmap += "*Generated by DevScope - Intelligent Codebase Analysis*\n\n"
        roadmap += "---\n\n"
        
        # Health score breakdown
        roadmap += self._generate_health_breakdown()
        roadmap += "\n---\n\n"
        
        # Priority sections
        roadmap += self._generate_priority_section("Critical", self.issues['critical'])
        roadmap += "\n---\n\n"
        
        roadmap += self._generate_priority_section("High", self.issues['high'])
        roadmap += "\n---\n\n"
        
        roadmap += self._generate_priority_section("Medium", self.issues['medium'])
        roadmap += "\n---\n\n"
        
        # Summary
        roadmap += self._generate_summary()
        
        logger.info(f"Roadmap generated: {len(self.issues['critical'])} critical, "
                   f"{len(self.issues['high'])} high, {len(self.issues['medium'])} medium priority items")
        
        return roadmap
    
    def _find_complexity_hotspots(self):
        """Find functions with high cyclomatic complexity."""
        logger.info("Finding complexity hotspots...")
        
        if self.neo4j_client.fallback_mode:
            logger.warning("Cannot find hotspots in fallback mode")
            return
        
        try:
            with self.neo4j_client.driver.session() as session:
                result = session.run(
                    """
                    MATCH (f:Function)
                    WHERE f.complexity > $threshold
                    RETURN f.name as name,
                           f.file_path as file,
                           f.complexity as complexity,
                           f.lines as lines
                    ORDER BY f.complexity DESC
                    LIMIT 20
                    """,
                    threshold=self.COMPLEXITY_THRESHOLD
                )
                
                hotspots = [dict(record) for record in result]
                
                for hotspot in hotspots:
                    priority = 'critical' if hotspot['complexity'] > 20 else 'high'
                    
                    self.issues[priority].append({
                        'type': 'complexity_hotspot',
                        'title': f"High Complexity: {hotspot['name']}()",
                        'description': f"Function has cyclomatic complexity of {hotspot['complexity']} "
                                     f"({hotspot['lines']} lines)",
                        'affected_files': [hotspot['file']],
                        'effort': 'medium' if hotspot['complexity'] < 25 else 'large',
                        'approach': "Break down into smaller functions, extract helper methods, "
                                  "simplify conditional logic"
                    })
                
                logger.info(f"Found {len(hotspots)} complexity hotspots")
                
        except Exception as e:
            logger.error(f"Error finding complexity hotspots: {e}")
    
    def _find_circular_dependencies(self):
        """Find circular dependencies in the codebase."""
        logger.info("Detecting circular dependencies...")
        
        try:
            cycles = self.neo4j_client.detect_cycles()
            
            for cycle in cycles[:10]:  # Limit to 10 cycles
                if len(cycle) > 1:
                    self.issues['critical'].append({
                        'type': 'circular_dependency',
                        'title': f"Circular Dependency: {len(cycle)} files",
                        'description': f"Circular import chain detected involving {len(cycle)} files",
                        'affected_files': cycle,
                        'effort': 'large',
                        'approach': "Refactor to break circular imports: extract shared code to new module, "
                                  "use dependency injection, or restructure module hierarchy"
                    })
            
            logger.info(f"Found {len(cycles)} circular dependencies")
            
        except Exception as e:
            logger.error(f"Error detecting circular dependencies: {e}")
    
    def _find_test_coverage_gaps(self):
        """Find files with no test coverage."""
        logger.info("Finding test coverage gaps...")
        
        if self.neo4j_client.fallback_mode:
            logger.warning("Cannot find coverage gaps in fallback mode")
            return
        
        try:
            with self.neo4j_client.driver.session() as session:
                result = session.run(
                    """
                    MATCH (f:File)
                    WHERE f.type = 'file' 
                    AND NOT (f)-[:TESTED_BY]->(:File)
                    AND f.complexity > 5
                    RETURN f.path as file,
                           f.complexity as complexity,
                           f.lines as lines
                    ORDER BY f.complexity DESC
                    LIMIT 15
                    """
                )
                
                untested = [dict(record) for record in result]
                
                for file in untested:
                    priority = 'high' if file['complexity'] > 10 else 'medium'
                    
                    self.issues[priority].append({
                        'type': 'no_tests',
                        'title': f"Missing Tests: {file['file']}",
                        'description': f"File has complexity {file['complexity']} but no test coverage",
                        'affected_files': [file['file']],
                        'effort': 'medium',
                        'approach': "Add unit tests covering main functionality, edge cases, and error handling"
                    })
                
                logger.info(f"Found {len(untested)} files without tests")
                
        except Exception as e:
            logger.error(f"Error finding test coverage gaps: {e}")
    
    def _find_anti_patterns(self):
        """Use Granite to detect anti-patterns in high-complexity files."""
        logger.info("Detecting anti-patterns with AI...")
        
        if self.granite_client.fallback_mode:
            logger.warning("Granite not available for anti-pattern detection")
            return
        
        # Get top complex files
        if self.neo4j_client.fallback_mode:
            return
        
        try:
            with self.neo4j_client.driver.session() as session:
                result = session.run(
                    """
                    MATCH (f:File)
                    WHERE f.complexity > 8
                    RETURN f.path as file,
                           f.complexity as complexity
                    ORDER BY f.complexity DESC
                    LIMIT 5
                    """
                )
                
                complex_files = [dict(record) for record in result]
                
                for file_info in complex_files:
                    file_path = self.repo_path / file_info['file']
                    
                    if not file_path.exists():
                        continue
                    
                    try:
                        with open(file_path, 'r', encoding='utf-8') as f:
                            content = f.read()
                        
                        # Get modernization opportunities from Granite
                        opportunities = self.granite_client.detect_modernization_opportunities(content)
                        
                        for opp in opportunities[:3]:  # Top 3 per file
                            severity = opp.get('severity', 'medium')
                            
                            if severity == 'high':
                                priority = 'high'
                            elif severity == 'medium':
                                priority = 'medium'
                            else:
                                priority = 'medium'
                            
                            self.issues[priority].append({
                                'type': 'anti_pattern',
                                'title': opp.get('issue', 'Code improvement opportunity'),
                                'description': opp.get('suggestion', 'See details'),
                                'affected_files': [file_info['file']],
                                'effort': opp.get('effort_estimate', 'medium'),
                                'approach': opp.get('suggestion', 'Refactor as suggested')
                            })
                        
                    except Exception as e:
                        logger.warning(f"Could not analyze {file_path}: {e}")
                        continue
                
                logger.info(f"Analyzed {len(complex_files)} files for anti-patterns")
                
        except Exception as e:
            logger.error(f"Error detecting anti-patterns: {e}")
    
    def _generate_health_breakdown(self) -> str:
        """Generate health score breakdown section."""
        section = "## 📊 Health Score Breakdown\n\n"
        
        total_issues = (len(self.issues['critical']) + 
                       len(self.issues['high']) + 
                       len(self.issues['medium']))
        
        # Calculate health score
        critical_penalty = len(self.issues['critical']) * 10
        high_penalty = len(self.issues['high']) * 5
        medium_penalty = len(self.issues['medium']) * 2
        
        health_score = max(0, 100 - critical_penalty - high_penalty - medium_penalty)
        
        if health_score >= 80:
            rating = "Excellent"
            emoji = "🟢"
        elif health_score >= 60:
            rating = "Good"
            emoji = "🟡"
        elif health_score >= 40:
            rating = "Fair"
            emoji = "🟠"
        else:
            rating = "Needs Attention"
            emoji = "🔴"
        
        section += f"**Overall Health**: {emoji} {health_score}/100 ({rating})\n\n"
        section += f"**Total Issues Found**: {total_issues}\n\n"
        section += "| Priority | Count | Impact |\n"
        section += "|----------|-------|--------|\n"
        section += f"| 🔴 Critical | {len(self.issues['critical'])} | Blocking issues, immediate action required |\n"
        section += f"| 🟠 High | {len(self.issues['high'])} | Significant tech debt, plan remediation |\n"
        section += f"| 🟡 Medium | {len(self.issues['medium'])} | Improvement opportunities, schedule when possible |\n\n"
        
        return section
    
    def _generate_priority_section(self, priority: str, issues: List[Dict[str, Any]]) -> str:
        """Generate a priority section of the roadmap."""
        emoji_map = {
            'Critical': '🔴',
            'High': '🟠',
            'Medium': '🟡'
        }
        
        section = f"## {emoji_map.get(priority, '⚪')} Priority {priority}\n\n"
        
        if not issues:
            section += f"*No {priority.lower()} priority issues found. Great job!*\n\n"
            return section
        
        section += f"**{len(issues)} issue(s) identified**\n\n"
        
        for i, issue in enumerate(issues, 1):
            section += f"### {i}. {issue['title']}\n\n"
            section += f"**Type**: {issue['type'].replace('_', ' ').title()}\n\n"
            section += f"**Description**: {issue['description']}\n\n"
            
            section += "**Affected Files**:\n"
            for file in issue['affected_files'][:5]:  # Limit to 5 files
                section += f"- `{file}`\n"
            if len(issue['affected_files']) > 5:
                section += f"- *...and {len(issue['affected_files']) - 5} more*\n"
            section += "\n"
            
            effort_emoji = {
                'small': '🟢',
                'medium': '🟡',
                'large': '🔴'
            }
            section += f"**Effort Estimate**: {effort_emoji.get(issue['effort'], '⚪')} "
            section += f"{issue['effort'].title()}\n\n"
            
            section += f"**Suggested Approach**:\n{issue['approach']}\n\n"
            section += "---\n\n"
        
        return section
    
    def _generate_summary(self) -> str:
        """Generate summary section."""
        section = "## 🎯 Implementation Strategy\n\n"
        section += "### Recommended Approach\n\n"
        section += "1. **Address Critical Issues First** (Week 1-2)\n"
        section += "   - Fix circular dependencies\n"
        section += "   - Refactor extreme complexity hotspots (>20)\n"
        section += "   - These block other improvements\n\n"
        
        section += "2. **Tackle High Priority Items** (Week 3-6)\n"
        section += "   - Add tests for complex untested code\n"
        section += "   - Refactor moderate complexity hotspots\n"
        section += "   - Address AI-detected anti-patterns\n\n"
        
        section += "3. **Continuous Improvement** (Ongoing)\n"
        section += "   - Address medium priority items in sprints\n"
        section += "   - Prevent new tech debt with code reviews\n"
        section += "   - Monitor complexity metrics\n\n"
        
        section += "### Success Metrics\n\n"
        section += "- Reduce average cyclomatic complexity to < 5\n"
        section += "- Achieve 80%+ test coverage\n"
        section += "- Eliminate all circular dependencies\n"
        section += "- Improve health score to 80+\n\n"
        
        section += "---\n\n"
        section += "*This roadmap was generated by DevScope. Prioritize based on your team's capacity "
        section += "and business needs. Re-run analysis after major changes to track progress.*\n"
        
        return section
    
    def get_summary_stats(self) -> Dict[str, Any]:
        """Get summary statistics for the roadmap."""
        return {
            'critical_count': len(self.issues['critical']),
            'high_count': len(self.issues['high']),
            'medium_count': len(self.issues['medium']),
            'total_count': sum(len(issues) for issues in self.issues.values())
        }


# Example usage
if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python modernization_planner.py <repo_path>")
        sys.exit(1)
    
    repo_path = sys.argv[1]
    
    planner = ModernizationPlanner(repo_path)
    roadmap = planner.generate_roadmap()
    
    # Save to file
    output_file = "MODERNIZATION_ROADMAP.md"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(roadmap)
    
    print(f"\n✓ Modernization roadmap generated: {output_file}")
    
    stats = planner.get_summary_stats()
    print(f"\nSummary: {stats['total_count']} total issues")
    print(f"  - Critical: {stats['critical_count']}")
    print(f"  - High: {stats['high_count']}")
    print(f"  - Medium: {stats['medium_count']}")

# Made with Bob
