"""
Onboarding Generator for DevScope.

Generates role-specific onboarding guides using:
- Neo4j graph data (PageRank, complexity, modules)
- Semantic enrichment (Granite LLM insights)
- Role-based filtering and prioritization
"""

from typing import Dict, Any, List, Optional
import logging
from ..graph.neo4j_client import Neo4jClient
from ..semantic.granite_client import GraniteClient

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class OnboardingGenerator:
    """
    Generates personalized onboarding guides for different developer roles.
    
    Creates markdown guides with:
    - Architecture overview
    - Critical files to read
    - Key patterns and conventions
    - Suggested first PR
    - Common gotchas
    """
    
    # Role-specific file patterns
    ROLE_PATTERNS = {
        'frontend': ['.jsx', '.tsx', '.vue', '.svelte', '.css', '.scss', 'component', 'ui', 'view'],
        'backend': ['.py', '.java', '.go', '.rs', 'api', 'service', 'controller', 'model', 'database'],
        'fullstack': [],  # All files
        'devops': ['docker', 'kubernetes', 'terraform', '.yml', '.yaml', 'deploy', 'ci', 'cd', 'infra']
    }
    
    def __init__(self, repo_path: str, neo4j_client: Optional[Neo4jClient] = None,
                 granite_client: Optional[GraniteClient] = None):
        """
        Initialize onboarding generator.
        
        Args:
            repo_path: Path to repository root
            neo4j_client: Optional Neo4j client (uses singleton if not provided)
            granite_client: Optional Granite client (creates new if not provided)
        """
        self.repo_path = repo_path
        self.neo4j_client = neo4j_client or Neo4jClient.get_instance()
        self.granite_client = granite_client or GraniteClient()
    
    def generate_guide(self, role: str = 'fullstack') -> str:
        """
        Generate complete onboarding guide for a role.
        
        Args:
            role: Developer role (frontend/backend/fullstack/devops)
            
        Returns:
            Markdown formatted onboarding guide
        """
        logger.info(f"Generating onboarding guide for role: {role}")
        
        role = role.lower()
        if role not in self.ROLE_PATTERNS:
            logger.warning(f"Unknown role '{role}', defaulting to 'fullstack'")
            role = 'fullstack'
        
        # Gather data
        modules = self._get_enriched_modules()
        critical_files = self._get_critical_files(role)
        patterns = self._extract_patterns(modules)
        entry_points = self._find_entry_points(role)
        
        # Build guide sections
        guide = f"# Your Onboarding Guide ({role.title()})\n\n"
        guide += f"*Generated by DevScope - Intelligent Codebase Onboarding*\n\n"
        guide += "---\n\n"
        
        # Architecture Overview
        guide += self._generate_architecture_section(modules, role)
        guide += "\n---\n\n"
        
        # Critical Files
        guide += self._generate_critical_files_section(critical_files, role)
        guide += "\n---\n\n"
        
        # Key Patterns
        guide += self._generate_patterns_section(patterns)
        guide += "\n---\n\n"
        
        # Suggested First PR
        guide += self._generate_first_pr_section(entry_points, role)
        guide += "\n---\n\n"
        
        # Common Gotchas
        guide += self._generate_gotchas_section(modules, role)
        guide += "\n---\n\n"
        
        # Next Steps
        guide += self._generate_next_steps_section(role)
        
        logger.info("Onboarding guide generated successfully")
        return guide
    
    def _get_enriched_modules(self) -> List[Dict[str, Any]]:
        """Get enriched modules from Neo4j."""
        if self.neo4j_client.fallback_mode:
            return []
        
        try:
            with self.neo4j_client.driver.session() as session:
                result = session.run(
                    """
                    MATCH (m:Module)
                    WHERE m.enriched = true
                    RETURN m.name as name,
                           m.purpose as purpose,
                           m.architectural_role as role,
                           m.patterns as patterns,
                           m.key_insight as insight,
                           m.onboarding_priority as priority,
                           m.file_count as file_count
                    ORDER BY 
                        CASE m.onboarding_priority
                            WHEN 'high' THEN 1
                            WHEN 'medium' THEN 2
                            ELSE 3
                        END,
                        m.avg_pagerank DESC
                    """
                )
                return [dict(record) for record in result]
        except Exception as e:
            logger.error(f"Failed to get enriched modules: {e}")
            return []
    
    def _get_critical_files(self, role: str, limit: int = 5) -> List[Dict[str, Any]]:
        """Get top critical files for a role using PageRank."""
        try:
            all_files = self.neo4j_client.run_pagerank(top_n=50)
            
            # Normalize: fallback mode returns 'node' key, Neo4j returns 'path'/'name'
            for f in all_files:
                if 'path' not in f:
                    f['path'] = f.get('node', f.get('name', 'Unknown'))
            
            # Filter by role
            patterns = self.ROLE_PATTERNS.get(role, [])
            if patterns:  # If role has specific patterns
                filtered = [
                    f for f in all_files
                    if any(pattern in f.get('path', '').lower() for pattern in patterns)
                ]
                # If not enough matches, include some general files
                if len(filtered) < limit:
                    filtered.extend([f for f in all_files if f not in filtered])
                return filtered[:limit]
            else:  # Fullstack - return top files
                return all_files[:limit]
                
        except Exception as e:
            logger.error(f"Failed to get critical files: {e}")
            return []
    
    def _extract_patterns(self, modules: List[Dict[str, Any]]) -> List[str]:
        """Extract unique design patterns from modules."""
        patterns = set()
        for module in modules:
            pattern_str = module.get('patterns', '')
            if pattern_str and pattern_str != 'None':
                # Split by common delimiters
                for p in pattern_str.replace(',', ' ').replace(';', ' ').split():
                    if p.strip():
                        patterns.add(p.strip())
        return sorted(list(patterns))
    
    def _find_entry_points(self, role: str) -> List[Dict[str, Any]]:
        """Find low-complexity entry points for first PR."""
        if self.neo4j_client.fallback_mode:
            return []
        
        try:
            with self.neo4j_client.driver.session() as session:
                result = session.run(
                    """
                    MATCH (f:File)
                    WHERE f.complexity < 5 AND f.lines < 200
                    RETURN f.path as path,
                           f.complexity as complexity,
                           f.lines as lines,
                           f.language as language
                    ORDER BY f.complexity ASC, f.lines ASC
                    LIMIT 10
                    """
                )
                files = [dict(record) for record in result]
                
                # Filter by role
                patterns = self.ROLE_PATTERNS.get(role, [])
                if patterns:
                    filtered = [
                        f for f in files
                        if any(pattern in f.get('path', '').lower() for pattern in patterns)
                    ]
                    return filtered[:3] if filtered else files[:3]
                return files[:3]
                
        except Exception as e:
            logger.error(f"Failed to find entry points: {e}")
            return []
    
    def _generate_architecture_from_graph(self, role: str) -> str:
        """Generate architecture overview from graph data when no enriched modules exist."""
        content = ""
        
        try:
            # Get communities for structure
            communities = self.neo4j_client.detect_communities()
            if communities:
                content += f"The codebase contains **{len(communities)} module clusters** "
                content += "identified through dependency analysis:\n\n"
                
                for i, comm in enumerate(communities[:5], 1):
                    members = comm.get('members', [])
                    size = comm.get('size', len(members))
                    # Show short filenames
                    display = [m.replace('\\', '/').split('/')[-1] for m in members[:4]]
                    preview = ', '.join(f"`{d}`" for d in display)
                    more = f" (+{size - 4} more)" if size > 4 else ""
                    content += f"**Cluster {i}** ({size} files): {preview}{more}\n\n"
            
            # Get top PageRank files
            top_files = self.neo4j_client.run_pagerank(top_n=5)
            if top_files:
                content += "### 🔑 Most Important Files\n\n"
                content += "These files are the most interconnected (highest PageRank):\n\n"
                for i, f in enumerate(top_files, 1):
                    path = f.get('path') or f.get('node', 'Unknown')
                    short = path.replace('\\', '/').split('/')[-1]
                    score = f.get('score', 0)
                    content += f"{i}. **{short}** — PageRank: {score:.4f}\n"
                content += "\n"
            
            if not content:
                content = "*Architecture analysis is available after running the full pipeline.*\n"
                
        except Exception as e:
            content = f"*Architecture data not available: {e}*\n"
        
        return content
    
    def _generate_architecture_section(self, modules: List[Dict[str, Any]], role: str) -> str:
        """Generate architecture overview section."""
        section = "## 🏗️ Architecture Overview\n\n"
        
        if not modules:
            # Provide a useful fallback using graph data
            section += self._generate_architecture_from_graph(role)
            return section
        
        # Group modules by architectural role
        role_groups = {}
        for module in modules:
            arch_role = module.get('role', 'Unknown')
            if arch_role not in role_groups:
                role_groups[arch_role] = []
            role_groups[arch_role].append(module)
        
        section += "The codebase is organized into the following architectural layers:\n\n"
        
        for arch_role, mods in sorted(role_groups.items()):
            section += f"### {arch_role}\n\n"
            for mod in mods[:3]:  # Top 3 per role
                section += f"**{mod['name']}** ({mod['priority']} priority)\n"
                section += f"- {mod.get('purpose', 'No description available')}\n"
                if mod.get('insight'):
                    section += f"- 💡 *{mod['insight']}*\n"
                section += f"- Files: {mod.get('file_count', 0)}\n\n"
        
        # Generate Granite summary
        context = {
            'role': role,
            'modules': [{'name': m['name'], 'purpose': m.get('purpose', '')} for m in modules[:5]],
            'total_modules': len(modules)
        }
        
        if not self.granite_client.fallback_mode:
            section += "### 🤖 AI-Generated Summary\n\n"
            summary = self.granite_client.generate_onboarding_section(context)
            section += summary + "\n\n"
        
        return section
    
    def _generate_critical_files_section(self, files: List[Dict[str, Any]], role: str) -> str:
        """Generate critical files section."""
        section = "## 📚 Critical Files to Read First\n\n"
        section += f"These files are most important for a {role} developer (ranked by PageRank):\n\n"
        
        if not files:
            section += "*No files found. Ensure graph has been built.*\n"
            return section
        
        for i, file in enumerate(files, 1):
            path = file.get('path') or file.get('node') or file.get('name', 'Unknown')
            # Clean path for display
            display_name = path.replace('\\', '/').split('/')[-1] if '/' in path or '\\' in path else path
            score = file.get('score', 0.0)
            file_type = file.get('type', 'file')
            
            # Get additional properties from fallback mode
            props = file.get('properties', {})
            complexity = props.get('complexity', file.get('complexity', 0))
            lines = props.get('lines', file.get('lines', 0))
            
            section += f"### {i}. `{path}`\n\n"
            section += f"- **Importance Score**: {score:.4f}\n"
            section += f"- **Type**: {file_type}\n"
            if complexity:
                section += f"- **Complexity**: {complexity}\n"
            if lines:
                section += f"- **Lines**: {lines}\n"
            
            # Get file explanation from Granite if available
            if not self.granite_client.fallback_mode and i <= 3:  # Only for top 3
                section += f"- **Why it matters**: *Analyzing...*\n"
            
            section += "\n"
        
        return section
    
    def _generate_patterns_section(self, patterns: List[str]) -> str:
        """Generate key patterns section."""
        section = "## 🎨 Key Patterns & Conventions\n\n"
        
        if not patterns:
            section += "*No patterns detected yet. Run semantic enrichment for pattern detection.*\n"
            return section
        
        section += "The codebase uses these design patterns and conventions:\n\n"
        
        for pattern in patterns[:10]:  # Top 10 patterns
            section += f"- **{pattern}**\n"
        
        section += "\n### 📖 Pattern Details\n\n"
        section += "*Refer to module documentation above for specific pattern implementations.*\n\n"
        
        return section
    
    def _generate_first_pr_section(self, entry_points: List[Dict[str, Any]], role: str) -> str:
        """Generate suggested first PR section."""
        section = "## 🚀 Suggested First PR\n\n"
        section += f"Good starting points for your first contribution as a {role} developer:\n\n"
        
        if not entry_points:
            section += "*No entry points identified. Look for files with low complexity.*\n"
            return section
        
        for i, file in enumerate(entry_points, 1):
            path = file.get('path', 'Unknown')
            complexity = file.get('complexity', 0)
            lines = file.get('lines', 0)
            
            section += f"### Option {i}: `{path}`\n\n"
            section += f"- **Complexity**: {complexity} (Low)\n"
            section += f"- **Size**: {lines} lines\n"
            section += f"- **Why**: Small, focused file - good for learning the codebase\n"
            section += f"- **Suggested tasks**: Add tests, improve documentation, refactor for clarity\n\n"
        
        return section
    
    def _generate_gotchas_section(self, modules: List[Dict[str, Any]], role: str) -> str:
        """Generate common gotchas section."""
        section = "## ⚠️ Common Gotchas\n\n"
        section += "Important things to watch out for:\n\n"
        
        # Extract insights from high-priority modules
        gotchas = []
        for module in modules:
            if module.get('priority') == 'high' and module.get('insight'):
                gotchas.append(f"- **{module['name']}**: {module['insight']}")
        
        if gotchas:
            section += "\n".join(gotchas[:5]) + "\n\n"
        else:
            section += "*No specific gotchas identified yet.*\n\n"
        
        section += "### General Best Practices\n\n"
        section += "- Read the README and CONTRIBUTING files\n"
        section += "- Check existing tests for usage examples\n"
        section += "- Ask questions in team channels\n"
        section += "- Start with small, focused changes\n\n"
        
        return section
    
    def _generate_next_steps_section(self, role: str) -> str:
        """Generate next steps section."""
        section = "## 🎯 Next Steps\n\n"
        section += "Your onboarding journey:\n\n"
        section += "1. **Week 1**: Read the critical files listed above\n"
        section += "2. **Week 2**: Explore the architecture and understand module relationships\n"
        section += "3. **Week 3**: Make your first PR (use suggested entry points)\n"
        section += "4. **Week 4**: Take on a small feature or bug fix\n"
        section += "5. **Ongoing**: Contribute to documentation and help other new team members\n\n"
        
        section += "### 📞 Getting Help\n\n"
        section += "- Check the project wiki/docs\n"
        section += "- Review closed PRs for examples\n"
        section += "- Reach out to module owners\n"
        section += "- Use DevScope dashboard for interactive exploration\n\n"
        
        section += "---\n\n"
        section += "*This guide was generated by DevScope. For the most up-to-date information, "
        section += "refer to the project documentation and team resources.*\n"
        
        return section


# Example usage
if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python onboarding_generator.py <repo_path> [role]")
        sys.exit(1)
    
    repo_path = sys.argv[1]
    role = sys.argv[2] if len(sys.argv) > 2 else 'fullstack'
    
    generator = OnboardingGenerator(repo_path)
    guide = generator.generate_guide(role)
    
    # Save to file
    output_file = f"ONBOARDING_{role.upper()}.md"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(guide)
    
    print(f"\n✓ Onboarding guide generated: {output_file}")
    print(f"\nPreview:\n{guide[:500]}...")

# Made with Bob
